import { GoogleGenerativeAI } from '@google/generative-ai';
import { Article } from '../models/Article';

/**
 * Service for integrating with Google Gemini API
 * Searches the web for articles and generates content
 */
export class GeminiService {
  private genAI: GoogleGenerativeAI | null = null;
  private model: any = null;

  constructor(apiKey?: string) {
    if (apiKey) {
      this.genAI = new GoogleGenerativeAI(apiKey);
      // Use gemini-2.0-flash-exp experimental model
      this.model = this.genAI.getGenerativeModel({ model: 'gemini-2.5-flash' });
    }
  }

  /**
   * Check if Gemini API is configured
   */
  isConfigured(): boolean {
    return this.genAI !== null;
  }

  /**
   * Search for articles on a specific topic using Gemini
   * @param topic - The topic to search for
   * @param count - Number of articles to generate (default: 5)
   * @returns Array of articles generated by Gemini
   */
  async searchArticles(topic: string, count: number = 5): Promise<Article[]> {
    if (!this.model) {
      throw new Error('Gemini API not configured. Please set GEMINI_API_KEY environment variable.');
    }

    const prompt = `Generate ${count} informative articles about "${topic}". 
For each article, create realistic information including:
- A compelling title
- An author name
- A recent publication date (2024)
- A category (Technology, Science, Business, Health, Sports, Politics, Entertainment, or Education)
- A 2-3 sentence summary
- 3-5 relevant tags
- A brief content excerpt (2-3 paragraphs)

Return ONLY a valid JSON array with no markdown formatting, no code blocks, no additional text:
[{"title":"...","author":"...","publicationDate":"2024-01-15","category":"...","summary":"...","tags":["..."],"content":"..."}]`;

    try {
      const result = await this.model.generateContent(prompt);
      const response = await result.response;
      let text = response.text().trim();
      
      console.log('Gemini raw response:', text.substring(0, 200));
      
      // Remove markdown code blocks if present
      text = text.replace(/```json\s*/g, '').replace(/```\s*/g, '');
      
      // Extract JSON from response
      const jsonMatch = text.match(/\[[\s\S]*\]/);
      if (!jsonMatch) {
        console.error('No JSON array found in response');
        throw new Error('Failed to parse articles from Gemini response');
      }

      const articlesData = JSON.parse(jsonMatch[0]);
      
      if (!Array.isArray(articlesData) || articlesData.length === 0) {
        throw new Error('No articles generated');
      }
      
      // Convert to Article objects
      const articles: Article[] = articlesData.map((data: any, index: number) => ({
        id: `gemini-${Date.now()}-${index}`,
        title: data.title || 'Untitled Article',
        author: data.author || 'Unknown Author',
        publicationDate: new Date(data.publicationDate || '2024-01-01'),
        category: data.category || 'General',
        summary: data.summary || 'No summary available',
        content: data.content || 'No content available',
        tags: Array.isArray(data.tags) ? data.tags : [],
        likeCount: 0,
        dislikeCount: 0,
        metadata: { source: 'gemini', searchTopic: topic }
      }));

      console.log(`Successfully generated ${articles.length} articles`);
      return articles;
    } catch (error: any) {
      console.error('Error searching articles with Gemini:', error);
      console.error('Error details:', error.message);
      throw new Error(`Failed to search articles: ${error.message}`);
    }
  }

  /**
   * Generate a conversational response using Gemini
   * @param message - User message
   * @param context - Conversation context
   * @returns Generated response
   */
  async generateResponse(message: string, context?: string): Promise<string> {
    if (!this.model) {
      throw new Error('Gemini API not configured');
    }

    const prompt = context 
      ? `Context: ${context}\n\nUser: ${message}\n\nAssistant:`
      : message;

    try {
      const result = await this.model.generateContent(prompt);
      const response = await result.response;
      return response.text();
    } catch (error) {
      console.error('Error generating response with Gemini:', error);
      throw new Error('Failed to generate response');
    }
  }

  /**
   * Enhance article search with natural language understanding
   * Extracts search intent and parameters from user message
   */
  async parseSearchIntent(message: string): Promise<{ topic: string; count: number }> {
    if (!this.model) {
      // Fallback to simple parsing
      return {
        topic: message.replace(/recommend|suggest|find|search|articles?|about/gi, '').trim(),
        count: 5
      };
    }

    const prompt = `Extract the search topic and desired number of articles from this message: "${message}"

Return ONLY a JSON object in this format:
{
  "topic": "extracted topic",
  "count": 5
}

If no specific count is mentioned, use 5. Only return the JSON, no other text.`;

    try {
      const result = await this.model.generateContent(prompt);
      const response = await result.response;
      const text = response.text();
      
      const jsonMatch = text.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        return JSON.parse(jsonMatch[0]);
      }
    } catch (error) {
      console.error('Error parsing search intent:', error);
    }

    // Fallback
    return {
      topic: message.replace(/recommend|suggest|find|search|articles?|about/gi, '').trim(),
      count: 5
    };
  }
}
